function export_summary_tables(stats_data, output_dir)
% EXPORT_SUMMARY_TABLES ส่งออกตารางสรุปข้อมูลสถิติและตัวชี้วัดเป็นไฟล์ .csv และ .mat
%
% ตารางที่ส่งออก:
%   1. table1_encoder_specifications.csv          - สเปค PPR, CPR, Resolution (deg & rad)
%   2. table2_mode_repeatability.csv               - สถิติการวัด X1, X2, X4 3 Trials (Mean, SD, %CV)
%   3. table3_speed_effect_analysis.csv           - ผลของความเร็ว (Slow, Normal, Fast: rad/s, RPM, Hz)
%   4. table4_homing_sequence_performance.csv      - ผลการทดลอง Homing Sequence และจุดศูนย์คาลิเบรต
%   5. table5_wraparound_validation.csv           - ผลการทดสอบ 16-bit Wrap-around Continuity
%   6. table6_analog_schmitt_metrics.csv          - สถิติสัญญาณ Optical Analog & Schmitt Trigger
%   7. lab1_3_summary_data.mat                    - ไฟล์โครงสร้างข้อมูล MATLAB แบบสมบูรณ์

    if nargin < 1 || isempty(stats_data)
        stats_data = process_static_data();
    end

    if nargin < 2 || isempty(output_dir)
        output_dir = fullfile(pwd, 'output_tables');
        if ~exist(output_dir, 'dir')
            cand = fullfile(pwd, 'MATLAB Visualize', 'output_tables');
            if exist(cand, 'dir')
                output_dir = cand;
            else
                mkdir(output_dir);
            end
        end
    end

    if ~exist(output_dir, 'dir')
        mkdir(output_dir);
    end

    fprintf('>> กำลังส่งออกตารางสรุปผลสถิติเป็นไฟล์ .csv และ .mat ใน: %s\n', output_dir);

    %% -------------------------------------------------------------------------
    % TABLE 1: Encoder Specifications (PPR, CPR, Angular Resolution)
    % -------------------------------------------------------------------------
    t1_rows = {};
    encoders = {'B', 'W'};
    modes = {'X1', 'X2', 'X4'};

    for e = 1:length(encoders)
        enc = encoders{e};
        for m = 1:length(modes)
            mod_str = modes{m};
            sp = stats_data.specifications.(enc).(mod_str);
            t1_rows = [t1_rows; { ...
                sprintf('Encoder_%s', enc), ...
                mod_str, ...
                sp.mult, ...
                sp.ppr_nominal, ...
                sp.ppr_measured, ...
                sp.cpr_nominal, ...
                sp.cpr_measured, ...
                sp.res_deg, ...
                sp.res_rad, ...
                sp.res_rad * 1000 ...
            }];
        end
    end

    t1 = cell2table(t1_rows, 'VariableNames', { ...
        'Encoder', 'Reading_Mode', 'Multiplier', ...
        'Nominal_PPR', 'Measured_PPR', 'Nominal_CPR', 'Measured_CPR', ...
        'Resolution_deg', 'Resolution_rad', 'Resolution_mrad' ...
    });
    t1_file = fullfile(output_dir, 'table1_encoder_specifications.csv');
    writetable(t1, t1_file);
    fprintf('   -> บันทึก: %s\n', t1_file);

    %% -------------------------------------------------------------------------
    % TABLE 2: Mode Repeatability (CW and CCW Across 3 Trials)
    % -------------------------------------------------------------------------
    t2_rows = {};
    for e = 1:length(encoders)
        enc = encoders{e};
        for m = 1:length(modes)
            mod_str = modes{m};
            sp = stats_data.specifications.(enc).(mod_str);

            % CW Row
            t2_rows = [t2_rows; { ...
                sprintf('Encoder_%s', enc), mod_str, 'CW', ...
                sp.cw_counts(1), sp.cw_counts(2), sp.cw_counts(3), ...
                sp.mean_cw, sp.std_cw, sp.cv_cw ...
            }];

            % CCW Row
            t2_rows = [t2_rows; { ...
                sprintf('Encoder_%s', enc), mod_str, 'CCW', ...
                sp.ccw_counts(1), sp.ccw_counts(2), sp.ccw_counts(3), ...
                sp.mean_ccw, sp.std_ccw, sp.cv_ccw ...
            }];
        end
    end

    t2 = cell2table(t2_rows, 'VariableNames', { ...
        'Encoder', 'Reading_Mode', 'Direction', ...
        'Trial_1_Counts', 'Trial_2_Counts', 'Trial_3_Counts', ...
        'Mean_Counts', 'Std_Dev_Counts', 'CV_Percent' ...
    });
    t2_file = fullfile(output_dir, 'table2_mode_repeatability.csv');
    writetable(t2, t2_file);
    fprintf('   -> บันทึก: %s\n', t2_file);

    %% -------------------------------------------------------------------------
    % TABLE 3: Speed Effect Analysis (Slow, Normal, Fast)
    % -------------------------------------------------------------------------
    t3_rows = {};
    for e = 1:length(encoders)
        enc = encoders{e};
        s_fields = fieldnames(stats_data.speed_analysis.(enc));
        for s = 1:length(s_fields)
            s_name = s_fields{s};
            spd = stats_data.speed_analysis.(enc).(s_name);
            t3_rows = [t3_rows; { ...
                sprintf('Encoder_%s', enc), s_name, spd.filename, ...
                spd.duration, spd.mean_vel_rad_s, spd.max_vel_rad_s, ...
                spd.mean_vel_rpm, spd.max_vel_rpm, ...
                spd.mean_pulse_freq_hz, spd.max_pulse_freq_hz ...
            }];
        end
    end

    t3 = cell2table(t3_rows, 'VariableNames', { ...
        'Encoder', 'Speed_Condition', 'Filename', ...
        'Duration_s', 'Mean_Velocity_rad_s', 'Max_Velocity_rad_s', ...
        'Mean_Velocity_RPM', 'Max_Velocity_RPM', ...
        'Mean_Pulse_Freq_Hz', 'Max_Pulse_Freq_Hz' ...
    });
    t3_file = fullfile(output_dir, 'table3_speed_effect_analysis.csv');
    writetable(t3, t3_file);
    fprintf('   -> บันทึก: %s\n', t3_file);

    %% -------------------------------------------------------------------------
    % TABLE 4: Homing Sequence Performance
    % -------------------------------------------------------------------------
    t4_rows = {};
    for k = 1:length(stats_data.homing)
        hm = stats_data.homing(k);
        t4_rows = [t4_rows; { ...
            k, hm.filename, hm.trigger_time_s, hm.raw_offset_rad, ...
            hm.calibrated_at_trigger, hm.cal_mean_locked, hm.cal_sd_locked, ...
            'Success' ...
        }];
    end

    t4 = cell2table(t4_rows, 'VariableNames', { ...
        'Trial', 'Filename', 'Trigger_Time_s', 'Raw_Offset_rad', ...
        'Calibrated_at_Trigger_rad', 'Post_Homing_Mean_rad', 'Post_Homing_SD_rad', ...
        'Status' ...
    });
    t4_file = fullfile(output_dir, 'table4_homing_sequence_performance.csv');
    writetable(t4, t4_file);
    fprintf('   -> บันทึก: %s\n', t4_file);

    %% -------------------------------------------------------------------------
    % TABLE 5: Wrap-around Logic Continuity Validation
    % -------------------------------------------------------------------------
    t5_rows = {};
    % Wrap Max (Overflow)
    for k = 1:length(stats_data.wraparound.max)
        wm = stats_data.wraparound.max(k);
        t5_rows = [t5_rows; { ...
            'Overflow (Wrap-Max)', k, wm.filename, wm.num_wraps, ...
            wm.first_wrap_time, wm.raw_before, wm.raw_after, ...
            wm.unwrapped_before, wm.unwrapped_after, wm.continuity_error, ...
            wm.peak_unwrapped_pulses, wm.peak_deg_continuous ...
        }];
    end

    % Wrap Min (Underflow)
    for k = 1:length(stats_data.wraparound.min)
        wn = stats_data.wraparound.min(k);
        t5_rows = [t5_rows; { ...
            'Underflow (Wrap-Min)', k, wn.filename, wn.num_wraps, ...
            wn.first_wrap_time, wn.raw_before, wn.raw_after, ...
            wn.unwrapped_before, wn.unwrapped_after, wn.continuity_error, ...
            wn.min_unwrapped_pulses, wn.min_deg_continuous ...
        }];
    end

    t5 = cell2table(t5_rows, 'VariableNames', { ...
        'Wrap_Type', 'Trial', 'Filename', 'Detected_Wraps', ...
        'First_Wrap_Time_s', 'Raw_Count_Before', 'Raw_Count_After', ...
        'Unwrapped_Before', 'Unwrapped_After', 'Continuity_Error_Pulses', ...
        'Peak_Unwrapped_Pulses', 'Peak_Degrees_Continuous' ...
    });
    t5_file = fullfile(output_dir, 'table5_wraparound_validation.csv');
    writetable(t5, t5_file);
    fprintf('   -> บันทึก: %s\n', t5_file);

    %% -------------------------------------------------------------------------
    % TABLE 6: Optical Analog & Schmitt Trigger Metrics
    % -------------------------------------------------------------------------
    t6_rows = {};
    for e = 1:length(encoders)
        enc = encoders{e};
        for d_dir = {'CW', 'CCW'}
            dir_str = d_dir{1};
            if isfield(stats_data.analog_schmitt.(enc), dir_str)
                an = stats_data.analog_schmitt.(enc).(dir_str);
                t6_rows = [t6_rows; { ...
                    sprintf('Encoder_%s', enc), dir_str, an.filename, ...
                    an.vA_min, an.vA_max, an.vA_pp, an.vA_mean, ...
                    an.vB_min, an.vB_max, an.vB_pp, an.vB_mean, ...
                    an.th_high_A, an.th_low_A, an.phase_lag_samples ...
                }];
            end
        end
    end

    t6 = cell2table(t6_rows, 'VariableNames', { ...
        'Encoder', 'Direction', 'Filename', ...
        'V_A_Min_V', 'V_A_Max_V', 'V_A_Vpp_V', 'V_A_Mean_V', ...
        'V_B_Min_V', 'V_B_Max_V', 'V_B_Vpp_V', 'V_B_Mean_V', ...
        'Schmitt_V_TH_High_V', 'Schmitt_V_TH_Low_V', 'Phase_Lag_Samples' ...
    });
    t6_file = fullfile(output_dir, 'table6_analog_schmitt_metrics.csv');
    writetable(t6, t6_file);
    fprintf('   -> บันทึก: %s\n', t6_file);

    %% -------------------------------------------------------------------------
    % SAVE MATLAB .MAT FILE (Complete Summary Dataset)
    % -------------------------------------------------------------------------
    mat_file = fullfile(output_dir, 'lab1_3_summary_data.mat');
    % เซฟตัวแปรสถิติและตาราง
    save(mat_file, 'stats_data', 't1', 't2', 't3', 't4', 't5', 't6', '-v7.3');
    fprintf('   -> บันทึกไฟล์ MAT: %s\n', mat_file);

    fprintf('>> ส่งออกตารางสรุปผลข้อมูลสถิติทั้งหมดเรียบร้อยแล้ว!\n');
end
